### ISSUE TITLE
Embeddings doesn't seem to work with LM Studio

### ISSUE THREAD

**Issue by elprl** [intitni/CustomSuggestionServiceForCopilotForXcode#16]
I add a new Model in Service -> Embedding Models section.

OpenAI Compatible
URL: http://192.168.50.201:1234/v1/embeddings
No API Key
Model: lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q8_0.gguf
Tokens: 8191

Run Test and get error: "No models loaded...."

Works fine in Chat Models (/v1/chat/completions)

**Comment by intitni** [comment]
But this extension doesn't use embedding models at all.

**Comment by intitni** [comment]
If the issue was for CopilotForXcode. Please don't worry about the embedding models for now, embedding features is not currently widely used in the app. I will rework on it later.

**Comment by elprl** [comment]
Chat model works with LM Studio. But I can't get it to work with the suggestion service. I have the extension enabled, but getting Error: The operation could not be completed. I've set the Feature provider in the Feature tab, but I don't see where to setup the base URL, etc. The Other Suggestion Services UI is just showing a 'Get It Now button'. Am I supposed to edit a file in this project before building?

**Comment by intitni** [comment]
I don't understand what you are trying to do. If you are using this app as the suggestion provider, you will have to do the settings in this app. Please check README.md for details.

**Comment by elprl** [comment]
Apologies, I built the project to the CopilotForXcodeExtension scheme and so didn't see the main application UI. It all makes sense now. You might want to mention in the readme to make sure to select the correct scheme. In fact, a screenshot of the UI in the readme would be even more helpful. And you don't even mention we can just download the pre-built .app file in the Releases link.
