### ISSUE TITLE
TODO: Trim the response suffix when they are identical to the request suffix

### ISSUE THREAD

**Issue by intitni** [intitni/CustomSuggestionServiceForCopilotForXcode#2]
Sometimes the models will generate trailing parenthesis even though they are already in the source code.

Can it be done by prompt engineering?

**Comment by MrDevel0per** [comment]
It might be possible to trim the response suffix by implementing "insertion" like this: https://openai.com/blog/gpt-3-edit-insert. I'm not sure if this is already how CopilotForXcode works but I think it is possible with GitHub Copilot as well.

**Comment by intitni** [comment]
Looks like CodeLlama supports a prompt format that can be used to generate fill-in-the-middle content https://ollama.com/library/codellama

**Comment by intitni** [comment]
Released in 0.2.0
