### ISSUE TITLE
The expanded panel remains blank

### ISSUE THREAD

**Issue by xiaooojun** [intitni/CustomSuggestionServiceForCopilotForXcode#9]
How to add ollama to an extension? Can you give a more detailed tutorial

**Comment by intitni** [comment]
<img width="829" alt="Screenshot 2024-06-06 at 16 08 23" src="https://github.com/intitni/CustomSuggestionServiceForCopilotForXcode/assets/793147/c0f0a17a-d62e-4ee6-9abd-112ad368a558">

**Comment by xiaooojun** [comment]
First of all, thank you for your timely reply, but I have a new problem now. After I integrated ollama, I haven't responded to my message for a long time until a timeout prompt appeared, but my ollama can work normally on the warp terminal.

**Comment by xiaooojun** [comment]
First of all, thank you for your timely reply, but I now have a new question. After adding ollama, I didn't respond to my messages for a long time until the timeout prompt appeared, but my ollama worked normally on the terminal.

**Comment by xiaooojun** [comment]
<img width="945" alt="image" src="https://github.com/intitni/CustomSuggestionServiceForCopilotForXcode/assets/130150746/e9dfd17a-07eb-4210-82ce-6a4aff2af328">

**Comment by intitni** [comment]
Do you have a screenshot about the timeout prompt?

**Comment by xiaooojun** [comment]
Now I can reply again, but the reply speed is very slow and it will take a long time to respond

**Comment by intitni** [comment]
The speed depends on your Mac. If you are using it to generate code completions, it's recommended to set a line limit to make it more usable.
